all:
	haxe -lib feathers -swf-lib Starling.swf -swf-lib Feathers.swf -swf-lib Feathers-MetalWorksMobileTheme.swf -swf-lib Feathers-MetalWorksMobileTheme.swf -main Test -swf test.swf -swf-header 640:360:60:ffffff
	open test.swf
